apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: talebook
  name: talebook
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: talebook
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: talebook
    spec:
      containers:
        - image: talebook/talebook
          name: talebook
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: talebook-claim0
      restartPolicy: Always
      volumes:
        - name: talebook-claim0
          persistentVolumeClaim:
            claimName: talebook-claim0
status: {}
